### PR TITLE
New HandBrake release 1.7.2

### PR DESCRIPTION
**Pull request by atesca09**
Updated to the latest handbrake release using the directions in the README.

bot,build

### CODE REVIEW

**Comment by jstebbins** [comment]
It appears flathub is now policing access to some permissions. It is rejecting the following in the manifest.
>         "--filesystem=xdg-config/gtk-3.0",

This permission was added a few years ago to permit showing of bookmarks in the file dialogs. I don't know if it is still needed given more recent changes to use xdg-desktop-portal. This will need testing.

If we still require this permission, instructions for requesting an exception are here https://docs.flathub.org/docs/for-app-authors/linter/#exceptions

**Comment by jstebbins** [comment]
... and now GitHub is stuck waiting for build status that seems to have already been delivered :disappointed:

**Comment by jstebbins** [comment]
Thanks @atesca09 :wave:

**Comment by Perkolator** [comment]
> This permission was added a few years ago to permit showing of bookmarks in the file dialogs. I don't know if it is still needed given more recent changes to use xdg-desktop-portal. This will need testing.

Doesn't seem to be needed anymore. I was the one that suggested that permission in the past. Still using the same linux release and just updated to 1.7.2. Bookmarks are available in the file dialogs without the permission.

**Pull request merged**
