### PR TITLE
update runtime org.gnome.Platform (from 46) to 47

### PR DESCRIPTION
**Pull request by zWhdmB5T**
update runtime org.gnome.Platform (from 46) to 47

### CODE REVIEW

**Comment by sr55** [comment]
Upgrades to the runtime must be made upstream and formally released.

**Comment by zWhdmB5T** [comment]
@sr55 I am sorry, that 1 is does not work and 2 this is formally the wrong way here.

**Comment by zWhdmB5T** [comment]
I formally close this PR due to reasons.

**Comment by zWhdmB5T** [comment]
To @jstebbins CC @sr55  
Can you please update all `runtime/org.freedesktop.Platform.*` of `flathub/fr.handbrake.ghb` from 23.08 to 24.08. Very appreciated. Thank you!

**Comment by sr55** [comment]
Handbrake 1.9 is coming soon with updated libraries.

**Comment by zWhdmB5T** [comment]
Sounds good. Thank you!

**Pull request closed without merging**
