### PR TITLE
Bump runtime to 40

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
Closes https://discourse.flathub.org/t/handbrake-gnome-3-36-eol/1253.

### CODE REVIEW

**Comment by Eonfge** [comment]
Forgive me for asking, but can't we just go to GNOME 40 directly? 3.38 and 40 share the same underlaying runtime (FreeDesktop 20.08) so every app that works with 3.38 will likely also work with 40.

**Comment by TheEvilSkeleton** [comment]
I guess that would work.

**Comment by TheEvilSkeleton** [comment]
bot, build

**Comment by jstebbins** [comment]
@sr55 I'll look at this on the weekend

**Comment by jstebbins** [comment]
When I run the updated flatpak I get a bunch of warnings
```
The peer-to-peer connection failed: Could not connect: Connection refused. Falling back to the session bus. Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
```

A recent update to gvfs seems to cause this.

I tried adding ```--filesystem=xdg-run/gvfsd``` to the manifest, but the warnings persist.  I'm guessing this is because my distro (fedora 33) does not have the updated gvfs and the gnome 40 flatpak platform does.

Any flatpak experts care to weigh in?  Can anyone comment on whether this will lead to any breakage? gvfs appears to be working, but I have no good way to test if adding ```--filesystem=xdg-run/gvfsd``` does the right thing when the environment is right.  And the spam warnings are kind of annoying and misleading for anyone that doesn't have the latest gvfs on their system.

It might be a good idea to stick to 3.38 till these gvfs changes are a bit more baked or more distros are on 40.

**Comment by TheEvilSkeleton** [comment]
Interesting. I think you're right. I am currently using Fedora 34 and I did not get any warnings.

**Comment by jstebbins** [comment]
If I understand you right, you don't get the warning even if ```--filesystem=xdg-run/gvfsd``` is *not* added to the manifest?  That makes the warning even more misleading and a bit mysterious.  Why is it there if that permission isn't needed.  Do you have any gvfs mounted filesystems (an SMB share is one thing you can mount via gvfs)?  I would like to know if they are showing in the filechooser when you try to open a source.

**Comment by TheEvilSkeleton** [comment]
Sorry for not being clear.

I *did* get the warning in Fedora Silverblue, until I added `--filesystem=xdg-run/gvfsd`. I used a Fedora 33 VM, and no matter what, I would get a warning.

Should I include `--filesystem=xdg-run/gvfsd` in the PR?

**Comment by jstebbins** [comment]
Yes please, add ```--filesystem=xdg-run/gvfsd```.  I can live with the warnings considering that new distro releases will fix them.

FYI, I also checked that the Intel Media SDK plugin works as expected.

Thanks!

**Pull request merged**
