### PR TITLE
Update libraries

### PR DESCRIPTION
**Pull request by darkdragon-001**
- Use flathub-external-data-checker for automatic update
- Prefer git type

Is there a machine-readable file (e.g. json) to read out the contribs versions?
See [flatpak-external-data-checker documentation](https://github.com/flathub/flatpak-external-data-checker#changes-to-flatpak-manifests) about available version checkers.

### CODE REVIEW

**Comment by darkdragon-001** [comment]
bot, build fr.handbrake.ghb

**Comment by jstebbins** [comment]
I like the changes, but as the README says...

All HandBrake development, including maintenance of Flatpak manifests, is performed in our [HandBrake GitHub repository](https://github.com/HandBrake/HandBrake). Please report any issues or create pull requests there.

In general, changes should be made in the HandBrake GitHub repo, directory pkg/linux/flatpak. The manifest there is used as a template for generating the manifest here when we do a new release.  The process is automated in our makefiles. This is also documented in the README here.

If I'm understanding correctly, you ran `flathub-external-data-checker` and saw some broken links and this is a submission to fix them? What specifically was broken? All the current links work fine for me and Gnome 41 has not yet been obsoleted. 

Generally, we only update this file when we make releases of HandBrake. And we use the same library versions as the releases for other platforms whenever possible (so that bugs are the same across platforms :stuck_out_tongue_winking_eye: ) But I will also update things here between releases if it can't be built for some reason (like a flatpak SDK becoming obsolete, which they do with annoying frequency).

**Comment by Erick555** [comment]
> If I'm understanding correctly, you ran flathub-external-data-checker and saw some broken links and this is a submission to fix them?

This PR will result with flathub bot creating new PRs with updates automatically for this repo. Since as you said the updates are done through handbrake repo first and the flathub bot perhaps  won't work there it doesn't make sense to have this chanages in either repo.

**Comment by darkdragon-001** [comment]
> But I will also update things here between releases if it can't be built for some reason (like a flatpak SDK becoming obsolete, which they do with annoying frequency).

@jstebbins Can we at least update the Platform/SDK version as Handbrake is one of the few applications still using Gnome 41?

For the other changes, I agree with @Erick555 that it doesn't make sense when you don't plan to upgrade the libraries here...

**Comment by jstebbins** [comment]
@darkdragon-001 I prefer to do such updates in the HandBrake repo so that the change does not accidentally get reverted when HandBrake puts out it's next release.

I also don't like releasing changes to FlatHub between HandBrake releases unless absolutely necessary. It makes tracking issues difficult if a problem turns out to be related to a mid-release change in behavior. We end up spending extra time re-diagnosing problems because we can't just point to a version and say "that version is known to have issue X".  It's rare, but platform changes have resulted in changes in behavior that users notice.

We create "nightly" flatpak bundles of latest code for anyone that wants to test bleeding edge releases.

**Comment by darkdragon-001** [comment]
@jstebbins How often is Handbrake released? GNOME is released every half year. So if a handbrake release happens timely after that, I think it is fine.

**Comment by darkdragon-001** [comment]
@jstebbins Do I see it correctly that it's already more than 4 months since the last point release? Should I add a PR for `master` and `1.5.x` branches?

Maybe it makes sense to integrate [`flatpak-external-data-checker`](https://github.com/flathub/flatpak-external-data-checker#custom-workflow) also in your repository as Github actions? This way, you should get automatic pull requests when dependencies change, your CI will run in this PR and when everything is fine, you only need to press the _merge_ button :wink: Unfortunately, platform updates are not supported yet (see flathub/flatpak-external-data-checker#161)...

**Comment by Erick555** [comment]
It was previously said that dependencies are synced cross-platform:

> And we use the same library versions as the releases for other platforms whenever possible (so that bugs are the same across platform

so auto updates for flatpak would be at odds with above.

**Comment by darkdragon-001** [comment]
@Erick555 does dependabot cover those dependencies then? I think some sort of automation makes sense...

**Comment by jstebbins** [comment]
The only dependency that will be visible to `flathub-external-data-checker` is libnuma I think. libnuma is not used by other platforms. Getting an automatic notification when that updates would be nice.

I'm currently "fixing" how libass gets built.  https://github.com/HandBrake/HandBrake/pull/4365

It *should* have been part of HandBrake's build process, but I took a shortcut a while back an threw it into the flatpak manifest.  Been manually keeping them in sync ever since, and doing a poor job of it :frowning_face:  So libass will be removed from the flatpak manifests.

**Comment by darkdragon-001** [comment]
@jstebbins sounds good to me :+1: 

So if you want the automatic notification for libnuma, feel free to copy the wanted parts from this PR and created the workflow according to the [`flathub-external-data-checker` docs](https://github.com/flathub/flatpak-external-data-checker#custom-workflow). If you need any help, just leave me a note :wink:

**Comment by rowbawts** [comment]
Any updates with this as the runtime being used is EOL.

```
Info: org.gnome.Platform//41 is end-of-life, with reason:
   The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.
```

**Comment by darkdragon-001** [comment]
In the meantime GNOME 43 has been released but Flathub package is still not updated. I updated this PR to the latest versions and also added a PR in the upstream repo (HandBrake/HandBrake#4629), again.

**Comment by darkdragon-001** [comment]
@nedrichards @barthalion any ideas why the build fails? The logs don't seem to show a build failure...

**Comment by barthalion** [comment]
```
error: /srv/buildbot/worker/build-x86_64-3/build/builddir/export/share/icons/hicolor/scalable/apps/fr.handbrake.ghb.svg is not a valid icon: Expected a square icon but got: 493x512
```

**Comment by darkdragon-001** [comment]
bot, build

**Comment by darkdragon-001** [comment]
I guess waiting until the next version is released...

**Comment by Erick555** [comment]
Hm, based on past discussion I thought this wasn't supposed to be merged, was it? @darkdragon-001 @jstebbins

**Comment by bradleysepos** [comment]
> Hm, based on past discussion I thought this wasn't supposed to be merged, was it? @darkdragon-001 @jstebbins

That's correct, @jstebbins mentioned this in https://github.com/flathub/fr.handbrake.ghb/pull/19#issuecomment-1126726172. So yes, the merge has essentially circumvented our release process ahead of the upcoming release.

**Comment by Erick555** [comment]
At least publishing this to flathub [failed](https://buildbot.flathub.org/#/builders/6/builds/5978). You may revert it in github if you want.

**Comment by Erick555** [comment]
It was stated that handbrake keep the same library versions across all platforms for easier debugability. I don't see any security vulnerabilities fixed in libass or numactl.

Developers said that SDK updates would be accepted on directly flathub  on flathub but one was done just today.

**Comment by darkdragon-001** [comment]
There have been multiple PRs in the Handbrake repository regarding Flatpak packaging since MAY (HandBrake/HandBrake#4364, HandBrake/HandBrake#4365, HandBrake/HandBrake#4629) but none of them has been released despite the claim that Handbrake is supposed to "fairly frequently" release minor upgrades.

**Comment by Erick555** [comment]
There wasn't any minor handbrake app update since Jan which is why flatpak didn't have any updates either.

**Comment by darkdragon-001** [comment]
Yes, but this isn't what I would call "fairly frequently" as it was claimed by @jstebbins. So I think there needs to be a different process to handle dependency updates as waiting 10 months is just too long in my opinion.

**Comment by bradleysepos** [comment]
Criticism received and accepted. In short, things change and we have had fewer active people and less available time for some months. We're working on updating things, and if anyone would like to help more directly with the Linux/GTK side (beyond simple dependency updates, but those count, too), feel free to connect with us on GitHub or IRC.

**Comment by Erick555** [comment]
But why do you need those dependency updates? Are they fixing some bug you found? This looks like update for the sake of update. I doubt handbrake users could tell the difference. I think that you provide solution without defining the problem.

As I understand developers want to control what they use in order to prevent unreproducible bugs and regressions.

**Comment by darkdragon-001** [comment]
> But why do you need those dependency updates? Are they fixing some bug you found? This looks like update for the sake of update. I doubt handbrake users could tell the difference. I think that you provide solution without defining the problem.

When there is a security vulnerability in one of the dependencies, it is important that there is a process in place to update to a fixed version as fast as possible. As no one in their free-time usually monitors all dependencies for reported vulnerabilities and being available all the time to manually fix it in a timely manner when it happens, I think automation can reduce the work significantly and increase security significantly.

**Comment by jstebbins** [comment]
As I said previously, changes here *will* be overwritten by whatever comes in the next handbrake release.  So what you have done here is temporary. If you would like permanent changes, you need to collaborate with the HandBrake project here https://github.com/HandBrake/HandBrake

I am not going to make any attempt to clean this mess up. We are short handed. I have had zero time to devote to HandBrake in quite some time. I am the only Linux developer. The others have done will to push things along on the Linux side of things, but it's not ideal. Help is wanted and appreciated, but it needs to be done in the correct repository.

**Comment by jstebbins** [comment]
I would also like to add that I didn't know others were authorized to make commits to this repo. Who else is authorized to do this. What has happened here is the equivalent of a supply chain attack. The HandBrake team has essentially lost control of our release.

**Comment by Erick555** [comment]
Yet there wasn't a security vulnerability fixed in your update and blindly pushing every update isn't replacement for app-development process.

I think it's quite clear that handbrake developers prefer stability and there are whole linux distros build around stability where libraries aren't updated for months or years unless there is specific reason to do so. What's happening here isn't any sort of uncommon thing.

It was explained in https://github.com/flathub/fr.handbrake.ghb/pull/19#issuecomment-1130031772 how yours approach may lead to more work rather than less.

**Comment by Erick555** [comment]
> I would also like to add that I didn't know others were authorized to make commits to this repo. Who else is authorized to do this? What has happened here is the equivalent of a supply chain attack. The HandBrake team has essentially lost control of our release.

The merge was done by flathub admin who may mistakenly thought this app was abandoned. In retrospect I think this PR should be closed in the beginning when it was clear there isn't intent to merge it.

**Comment by sr55** [comment]
>To be fair @darkdragon-001 is active contributor in main handbrake github repo

This individual currently has  a total of 2 commits. (Which we do appreciate by the way) but we don't have a trust relationship with them.  PR's are validated before they are blindly accepted on our main repo. The CI process needs approved for non project members before it's allowed to run also.

> little disappointment when no changes were pushed back here especially the SDK update while the one used on flathub had EOL status.

Yeh, Absolutely that's on us.  We are extremely resource starved so it's unfortunately difficult for us to move fast. That said, we are generally responsive if pinged.

I believe Flathub admins should have the point of contacts on this repo which sound be pinged first as a point of call before accepting 3rd party contributions.  It's not far fetched to think of a possible scenario where someone submits an innocent looking PR that includes compromised code. 

My suggestion would be, a failure of upstream to respond leads to package suspension on flathub in the event of security or dependency problems. 

Ultimately, it would be better for us to be in a suspended state, than untrusted / unverified induvial contributing changes not validated by the upstream project.

**Pull request merged**
